name: Build APK Expo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Expo CLI dan Dependencies
        run: |
          npm install -g expo-cli
          npm install --legacy-peer-deps

      - name: Generate Folder Android (Prebuild)
        run: npx expo prebuild --platform android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: HuaweiManager-Fixed
          path: android/app/build/outputs/apk/release/*.apk
