name: Build APK Final Fix
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Gunakan versi 20 agar kompatibel dengan reanimated

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npx expo install --fix

      - name: Hapus Referensi Google Services
        run: |
          sed -i '/googleServicesFile/d' app.config.ts || true
          sed -i '/googleServicesFile/d' app.json || true

      - name: Generate Folder Android
        run: npx expo prebuild --platform android --no-install

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: HuaweiManager-E5577-Fix
          path: android/app/build/outputs/apk/release/*.apk
